---
# YAML based inventory can make it easier to pass custom vars, see:
# https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
#
# Here's an example with additional variables:
#
#all:
#  hosts:
#    localhost:
#      ansible_connection: local
#      korora_packages_custom:
#        install:
#          - nano
#        remove:
#          - nano
#  vars:
#    ansible_python_interpreter: /usr/bin/python3

# Local connection doesn't require ssh
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
